name: Playwright Tests
on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          
      - name: Install dependencies
        working-directory: demo-framework
        run: |
          npm install
          npx playwright install --with-deps

      - name: Install app dependencies
        working-directory: pw-practice-app
        run: npm install --force

      - name: Run tests
        working-directory: demo-framework
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: demo-framework/playwright-report/
          retention-days: 30
